### ISSUE TITLE
License

### ISSUE THREAD

**Issue by PhilippJunk** [pymodproject/altmod#1]
Hi, 

I would like to use your plugin for a project.
Could you tell me what the license is?

https://choosealicense.com/no-permission/
https://opensource.stackexchange.com/q/1720

Thank you!
Philipp

**Comment by giacomojanson** [comment]
Thank you for having noted this. I added a LICENSE file (MIT License).
Best

Giacomo

**Comment by PhilippJunk** [comment]
Thank you!

Best
Philipp
